version: "3"
services:

  db:
    image: postgres:16-bullseye
    environment:
      POSTGRES_PASSWORD: Joi79007295
      POSTGRES_USER: Joi
    volumes:
      - joi_db_volume:/var/lib/postgresql/data

  backend:
    build: "./backend"
    volumes:
      - joi_files_volume:/app/public
    ports:
      - 3673:3673
    depends_on:
      - db
    environment:
      PG_URI: postgres://Joi:Joi79007295@db:5432/Joi
    restart: always

  frontend:
    image: nginx
    ports:
      - 81:80
    volumes:
      - ./nginx_site.conf:/etc/nginx/conf.d/default.conf:ro
      - ./frontend/dist:/usr/share/nginx/html:ro
    environment:
      VITE_API_URL: /api
    depends_on:
      - backend

volumes:
  joi_db_volume:
  joi_files_volume: